# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0dfe7194e1db8fd266bb97dbc6435a1b60c6f4167b3e0333cdeda4f2bb6c3a4789ceeaf14f07757fb7b3e263158ef6e286c5299ee555bb8807df0ebba58d5bb7

test:
  secret_key_base: f743e65019da5d2a2b5879606c7fd37c4598a85e8bb5fdd98c7e720d4527934038516f562524fbc3d2704565d6d7f60ff6dab1b2b2b9423b3f27c61712fe7499

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
